version: '3.8'

services:
  db:
    image: postgres:15
    container_name: medicare_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - medicare_network

  web:
    build: .
    container_name: medicare_web
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file:
      - .env
    networks:
      - medicare_network

  redis:
    image: redis:7-alpine
    container_name: medicare_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - medicare_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  medicare_network:
    driver: bridge